##
# -- IO Config --
#
#   - lid:LogSource_unix
#   - lid:LogSource_apache
#   - lid:LogSource_audit
#   - lid:LogSource_ftp
##

source: auth.log
format: "<Device> <Month> <Date> <Time> <Type> <Component>: <Content>"
rawFolder: input/
initializedFolder: output/auth.log/1-init
preprocessedFolder: output/auth.log/2-logpai

sourceLogpai: output/auth.log/2-logpai/auth.log_structured.csv
sourceLogpaiTemplate: output/auth.log/2-logpai/auth.log_templates.csv

logFormat: unix
logSourceType: auth

isOverrideExisting: false
paramExtractAttempt: 3
logEventsPerExtraction: 2000

targetOttr: output/auth.log/3-ottr
targetOttrBase: output/auth.log/3-ottr
targetOttrTurtle: output/auth.log/4-ttl

targetStanfordNer: output/auth.log/ner.rules
targetConfigTimer: output/timer.csv
targetConfigTurtle: output/auth.log/auth.log-template.ttl


