namespaces:
  - prefix: rdf
    uri: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  - prefix: rdfs
    uri: http://www.w3.org/2000/01/rdf-schema#
  - prefix: owl
    uri: http://www.w3.org/2002/07/owl#
  - prefix: xsd
    uri: http://www.w3.org/2001/XMLSchema#
  - prefix: ottr
    uri: http://ns.ottr.xyz/0.4/
  - prefix: log
    uri: https://w3id.org/sepses/ns/log#
  - prefix: logex
    uri: https://w3id.org/sepses/ns/logex#
  - prefix: lid
    uri: https://w3id.org/sepses/id/log/
  - prefix: lxid
    uri: https://w3id.org/sepses/id/logex/
  - prefix: svid
    uri: https://w3id.org/sepses/id/service/
  - prefix: cee
    uri: https://w3id.org/sepses/cee#

logFormats:
  - id: ftp
    ottrBaseTemplate: lxid:OttrTemplate_ftp
    header: LineId,Device,dayOfWeek,month,day,time,year,pid,pidNumber,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: month,day,time,year
    parameters:
      - column: pidNumber
        property: log:pid
  - id: unix
    ottrBaseTemplate: lxid:OttrTemplate_unix
    header: LineId,Device,Month,Date,Time,Type,Component,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: Month,Date,Time
    functions:
      - columns: Component
        function: getPidPname
  - id: audit
    ottrBaseTemplate: lxid:OttrTemplate_audit
    header: LineId,Device,type,time,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: time
    parameters:
      - column: type
        property: log:cmd
  - id: apache
    ottrBaseTemplate: lxid:OttrTemplate_apache
    header: LineId,Device,IP,DateTime,TimeZone,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: DateTime,TimeZone
    functions:
      - columns: IP
        function: getIp
  - id: suricata
    ottrBaseTemplate: lxid:OttrTemplate_event
    header: LineId,Device,day,month,year,Time,ms,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: day,month,year,Time,ms
    functions:
  - id: exim
    ottrBaseTemplate: lxid:OttrTemplate_event
    header: LineId,Device,year,month,day,Time,Content,EventId,EventTemplate,ParameterList
    host: Device
    content: Content
    time: day,month,year,Time
    functions:


nerParameters:
  - id: ip
    pattern: ([{word:/(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/}])
    action: Annotate($0, ner, "ip")
    function: object log:IPv4
    ottrTemplate:
      uri: lxid:OttrTemplate_ip
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?ip
        - xsd:string ?ipString
      functions: 
        - ottr:Triple(?id,log:hasIPv4,?ip)
        - ottr:Triple(?ip,rdf:type,log:IPv4)
        - ottr:Triple(?ip,log:ipv4,?ipString)
  - id: port
    pattern: ([{word:/port/}] + ([{word:/(\d{1,5})/}]))
    action: Annotate($1, ner, "port")
    function: portCreation
    ottrTemplate:
      uri: lxid:OttrTemplate_port
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?port # lid:Address_8080
        - ottr:IRI ?linkedPort # port:Port_8080
        - xsd:integer ?portInt # 8080
      functions: 
        - ottr:Triple(?id,log:hasPort,?port)
        - ottr:Triple(?port,rdf:type,log:Port)
        - ottr:Triple(?port,log:port,?portInt)
        - ottr:Triple(?port,log:linkedPortService,?linkedPort)
  - id: host
    pattern: ([{word:/hostname/}] + [{word:/:|-|=|\s/}]? ([{word:/(\w+)/}]))
    action: Annotate($1, ner, "host")
    function: object log:Host
    ottrTemplate:
      uri: lxid:OttrTemplate_host
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions: 
        - ottr:Triple(?id,log:hasHost,?obj)
        - ottr:Triple(?obj,rdf:type,log:Host)
        - ottr:Triple(?obj,log:host,?objString)
  - id: domain
    pattern: ([{word:/((?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+[A-Za-z]{2,6}/}])
    action: Annotate($0, ner, "domain")
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_domain
      parameters: 
        - ottr:IRI ?id
        - xsd:string ?objString
      functions: 
        - ottr:Triple(?id,log:domainName,?objString)
  - id: user # ESWC - [uU]
    pattern: ([{word:/r?[uU]ser/}]+ [{word:/:|-|=|\s/}]? ([{word:/\<?(\w+)\>?/}]))
    action: Annotate($1, ner, "user")
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_user
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: pid # ESWC - added pid detection
    pattern: ([{word:/pid/}]+ [{word:/:|-|=|\s/}] ([{word:/(\d+)/}]))
    action: Annotate($1, ner, "pid")
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_pid
      parameters:
        - ottr:IRI ?id
        - xsd:integer ?pid
      functions:
        - ottr:Triple(?id,log:pid,?pid)
  - id: userPassword
    pattern: ([{word:/password/}] [{word:/for/}] ([{word:/(\w+)/}]))
    action: Annotate($1, ner, "userPassword")
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_userPassword
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: email # ESWC - add implementation
    pattern: ([{word:/^<?[a-zA-Z0-9.!#$%&'*+\/?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*>?$/}])
    action: Annotate($0, ner, "email")
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_email
      parameters:
        - ottr:IRI ?id
        - xsd:string ?email
      functions:
        - ottr:Triple(?id, log:email, ?email)

## WARNING: id and ottrTemplate must be unique for each nonNerParameter!!!
## @14.06.2021
nonNerParameters:
  - id: path
    pattern: "[a-zA-Z0-9-_\\+&@#%~]+/[a-zA-Z0-9-_\\+&#%~/]+"
    action:
    function: object log:File
    ottrTemplate:
      uri: lxid:OttrTemplate_path
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?path
        - xsd:string ?pathString
      functions:
        - ottr:Triple(?id,log:hasFile,?path)
        - ottr:Triple(?path,rdf:type,log:File)
        - ottr:Triple(?path,log:file.path,?pathString)
  - id: filePath
    pattern: "(^|\\s+)\\[?\\\\?\"?([a-zA-Z0-9-_\\+&#%~/\\.]+\\.[a-zA-Z]{3,4}+)" #  @14.06.2021
    action:
    function: filePathSplit
    ottrTemplate:
      uri: lxid:OttrTemplate_filePath
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?path
        - xsd:string ?pathString
        - xsd:string ?fileString
      functions:
        - ottr:Triple(?id,log:hasFile,?path)
        - ottr:Triple(?path,rdf:type,log:File)
        - ottr:Triple(?path,log:file.path,?pathString)
        - ottr:Triple(?path,log:file.name,?fileString)
  - id: url
    pattern: "(https?|ftp|file):[a-zA-Z0-9-_/\\.\\\\]+\\.[a-zA-Z]{3,4}(/[a-zA-Z0-9-_\\+&@#%~/\\./]+)?"
    action:
    function: object log:URL
    ottrTemplate:
      uri: lxid:OttrTemplate_URL
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?url
        - xsd:string ?urlString
      functions:
        - ottr:Triple(?id,log:hasURL,?url)
        - ottr:Triple(?url,rdf:type,log:URL)
        - ottr:Triple(?url,log:url.url,?urlString)
  - id: urlWithParameters
    pattern: "(https?|ftp|file):[a-zA-Z0-9-_/\\.\\\\]+\\.[a-zA-Z]{3,4}(/[a-zA-Z0-9-_\\+&@#%~/\\./]+)?\\?[a-zA-Z]+\\=[a-zA-Z1-9&=\\+]+"
    action: 
    function: splitUrlParameter
    ottrTemplate:
      uri: lxid:OttrTemplate_urlWithParameters
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?url
        - xsd:string ?urlString
        - xsd:string ?paramString
      functions: 
        - ottr:Triple(?id,log:hasURL,?url)
        - ottr:Triple(?url,rdf:type,log:URL)
        - ottr:Triple(?url,log:url.url,?urlString)
        - ottr:Triple(?url,log:url.param,?paramString)
  - id: ipWithPrefix
    pattern: "[a-f]{4}\\:(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})"
    action: 
    function: ipWithPrefix
    ottrTemplate:
      uri: lxid:OttrTemplate_ipWithPrefix
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?ip
        - xsd:string ?ipString
      functions: 
        - ottr:Triple(?id,log:hasIPv4,?ip)
        - ottr:Triple(?ip,rdf:type,log:IPv4)
        - ottr:Triple(?ip,log:ipv4,?ipString)
  - id: ipWithPort # added for ESWC
    pattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\:(\\d{1,5})"
    action:
    function: ipWithPort
    ottrTemplate:
      uri: lxid:OttrTemplate_ipWithPort
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?ip
        - xsd:string ?ipString
        - ottr:IRI ?port # lid:Address_8080
        - ottr:IRI ?linkedPort # port:Port_8080
        - xsd:integer ?portInt # 8080
      functions:
        - ottr:Triple(?id,log:hasIPv4,?ip)
        - ottr:Triple(?ip,rdf:type,log:IPv4)
        - ottr:Triple(?ip,log:ipv4,?ipString)
        - ottr:Triple(?id,log:hasPort,?port)
        - ottr:Triple(?port,rdf:type,log:Port)
        - ottr:Triple(?port,log:port,?portInt)
        - ottr:Triple(?port,log:linkedPortService,?linkedPort)
#  - id: ftpUser # NOTE: too many false positive @14.06.2021
#    pattern: "^\\[([a-zA-Z][a-zA-Z0-9_\\.+]+)\\]"
#    action:
#    function: object log:User
#    ottrTemplate:
#      uri: lxid:OttrTemplate_ftpUser
#      parameters:
#        - ottr:IRI ?id
#        - ottr:IRI ?obj
#        - xsd:string ?objString
#      functions:
#        - ottr:Triple(?id,log:hasUser,?obj)
#        - ottr:Triple(?obj,rdf:type,log:User)
#        - ottr:Triple(?obj,log:user.name,?objString)
  - id: userLogin #  @14.06.2021
    pattern: "Login success for ([a-zA-Z0-9]+)"
    action:
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_userLogin
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: loginForUser #  @14.06.2021
    pattern: "[Ll][Oo][Gg][Ii][Nn]\\s+[Ff][Oo][Rr]\\s+(\\w+)"
    action:
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_loginForUser
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: sentToUser #  @14.06.2021
    pattern: "sent to\\s+(\\w+)"
    action:
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_sentToUser
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: fromUser #  @14.06.2021
    pattern: "from\\s+(\\w+)"
    action:
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_fromUser
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: userImap # ESWC
    pattern: "imap\\(([a-zA-Z0-9]+)\\)"
    action:
    function: object log:User
    ottrTemplate:
      uri: lxid:OttrTemplate_userImap
      parameters:
        - ottr:IRI ?id
        - ottr:IRI ?obj
        - xsd:string ?objString
      functions:
        - ottr:Triple(?id,log:hasUser,?obj)
        - ottr:Triple(?obj,rdf:type,log:User)
        - ottr:Triple(?obj,log:user.name,?objString)
  - id: group
    pattern: "group: name\\=([a-zA-Z0-9_\\.]+)"
    action: 
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_group
      parameters: 
        - ottr:IRI ?id
        - xsd:string ?objString
      functions: 
        - ottr:Triple(?id,log:group,?objString)
  - id: mac
    pattern: "([A-Fa-f0-9]{2}:){5}[A-Fa-f0-9]{2}"
    action: 
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_mac
      parameters: 
        - ottr:IRI ?id
        - xsd:string ?mac
      functions: 
        - ottr:Triple(?id,log:mac,?mac)
  - id: ciscoMac
    pattern: "([A-Fa-f0-9]{4}\\.){2}[A-Fa-f0-9]{4}"
    action: 
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_ciscoMac
      parameters: 
        - ottr:IRI ?id
        - xsd:string ?mac
      functions: 
        - ottr:Triple(?id,log:ciscoMac,?mac)
  - id: ipv6
    pattern: "((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:)))(%.+)?"
    action: 
    function: object log:IPv6
    ottrTemplate:
      uri: lxid:OttrTemplate_ipv6
      parameters: 
        - ottr:IRI ?id
        - ottr:IRI ?ip
        - xsd:string ?ipString
      functions: 
        - ottr:Triple(?id,log:hasIPv6,?ip)
        - ottr:Triple(?ip,rdf:type,log:IPv6)
        - ottr:Triple(?ip,log:ipv6,?ipString)
  - id: exe
    pattern: "exe\\=\"[a-zA-Z0-9-_\\./]+"
    action: 
    function: literal
    ottrTemplate:
      uri: lxid:OttrTemplate_exe
      parameters: 
        - ottr:IRI ?id
        - xsd:string ?objString
      functions: 
        - ottr:Triple(?id,log:cmd,?objString)


ottrTemplates: 
  - uri: lxid:OttrTemplate_event
    parameters: 
      - ottr:IRI ?id
      - ottr:IRI ?hostUrl
      - xsd:string ?hostString
      - xsd:dateTime ?timestamp
      - xsd:string ?message
      - ottr:IRI ?template
      - ottr:IRI ?logSource
    functions: 
      - ottr:Triple(?id,rdf:type,log:Event)
      - ottr:Triple(?id,log:hasSourceHost,?hostUrl)
      - ottr:Triple(?hostUrl,rdf:type,log:Host)
      - ottr:Triple(?hostUrl,log:host,?hostString)
      - ottr:Triple(?id,log:time,?timestamp)
      - ottr:Triple(?id,log:msg,?message)      
      - ottr:Triple(?id,logex:template,?template)
      - ottr:Triple(?id,log:hasSource,?logSource)

  - uri: lxid:OttrTemplate_unix
    parameters: 
      - ottr:IRI ?id
      - ottr:IRI ?hostUrl
      - xsd:string ?hostString
      - xsd:dateTime ?timestamp
      - xsd:string ?message
      - ottr:IRI ?template
      - ottr:IRI ?logSource
      - xsd:string ?pname        
      - xsd:string ?pid
    functions: 
      - lxid:OttrTemplate_event(?id,?hostUrl,?hostString,?timestamp,?message,?template,?logSource)
      - ottr:Triple(?id,log:pid,?pid)
      - ottr:Triple(?id,log:pname,?pname)

  - uri: lxid:OttrTemplate_ftp
    parameters: 
      - ottr:IRI ?id
      - ottr:IRI ?hostUrl
      - xsd:string ?hostString
      - xsd:dateTime ?timestamp
      - xsd:string ?message
      - ottr:IRI ?template
      - ottr:IRI ?logSource
      - xsd:string ?pid
    functions: 
      - lxid:OttrTemplate_event(?id,?hostUrl,?hostString,?timestamp,?message,?template,?logSource)
      - ottr:Triple(?id,log:pid,?pid)

  - uri: lxid:OttrTemplate_audit
    parameters: 
      - ottr:IRI ?id
      - ottr:IRI ?hostUrl
      - xsd:string ?hostString
      - xsd:dateTime ?timestamp
      - xsd:string ?message
      - ottr:IRI ?template
      - ottr:IRI ?logSource
      - xsd:string ?cmd
    functions: 
      - lxid:OttrTemplate_event(?id,?hostUrl,?hostString,?timestamp,?message,?template,?logSource)
      - ottr:Triple(?id,log:cmd,?cmd)

  - uri: lxid:OttrTemplate_apache
    parameters: 
      - ottr:IRI ?id
      - ottr:IRI ?hostUrl
      - xsd:string ?hostString
      - xsd:dateTime ?timestamp
      - xsd:string ?message
      - ottr:IRI ?template
      - ottr:IRI ?logSource
      - ottr:IRI ?ip
      - xsd:string ?ipString
    functions: 
      - lxid:OttrTemplate_event(?id,?hostUrl,?hostString,?timestamp,?message,?template,?logSource)
      - ottr:Triple(?id,log:hasIPv4,?ip)
      - ottr:Triple(?ip,rdf:type,log:IPv4)
      - ottr:Triple(?ip,log:ipv4,?ipString)

  - uri: lxid:OttrTemplate_unknown
    parameters: 
      - ottr:IRI ?id
      - xsd:string ?unknown
    functions: 
      - ottr:Triple(?id,log:contain,?unknown)

  - uri: lxid:OttrTemplate_Source
    parameters:
      - ottr:IRI ?logSource
      - xsd:string ?logSourceString
      - ottr:IRI ?sourceType
      - xsd:string ?sourceTypeString
      - ottr:IRI ?logFormat
      - xsd:string ?logFormatString
    functions:
      - ottr:Triple(?logSource,rdf:type,log:Source)
      - ottr:Triple(?logSource,rdfs:label,?logSourceString)
      - ottr:Triple(?logSource,log:hasSourceType,?sourceType)
      - ottr:Triple(?sourceType,rdf:type,log:SourceType)
      - ottr:Triple(?sourceType,rdfs:label,?sourceTypeString)
      - ottr:Triple(?sourceType,log:hasFormat,?logFormat)
      - ottr:Triple(?logFormat,rdf:type,log:Format)
      - ottr:Triple(?logFormat,rdfs:label,?logFormatString)









